export interface RawTrack {
    artwork_url: string,
    caption: string | null,
    commentable: boolean,
    comment_count: number,
    created_at: string,
    description: string | null,
    downloadable: boolean,
    download_count: number,
    duration: number,
    full_duration: number,
    embeddable_by: string,
    genre: string,
    has_downloads_left: boolean,
    id: number,
    kind: string,
    label_name: string | null,
    last_modified: string,
    license: string,
    likes_count: number,
    permalink: string,
    permalink_url: string,
    playback_count: number,
    public: boolean,
    publisher_metadata: string | null,
    purchase_title: string | null,
    purchase_url: string | null,
    release_date: string | null,
    reposts_count: number,
    secret_token: string | null,
    sharing: string,
    state: string,
    streamable: boolean,
    ag_list: string | null,
    title: string,
    track_format: string,
    uri: string,
    urn: string,
    user_id: number,
    isuals: string | null,
    waveform_url: string,
    display_date: string,
    media: object,
    station_urn: string,
    station_permalink: string,
    track_authorization: string,
    monetization_model: string,
    policy: string,
    user: object,
}
