import { Comment } from "./comment";

export interface Track {
    id: number,
    title: string,
    description: string | null,
    image: string | null,
    duration: number,
    playCount: string,
    downloadCount: string,
    commentCount: number,
    likesCount: number,
    genre: string | null,
    purchaseURL: string | null,
    tags: string | string[] | null,
    author: {
        id: number,
        name: string,
        username: string,
        avatarURL: string | null,
        createdAt: string | null,
        createdAtF: string | null,
        followersCount: number,
        followingsCount: number,
        groupsCount: number,
        firstName: string,
        lastName: string | null,
        fullName: string | null,
        lastModified: string | null,
        lastModifiedF: string | null,
        likesCount: number,
        urn: string,
        verified: boolean,
    },
    publisher: string | null,
    publishedAt: string,
    publishedAtF: string,
    media: [
        {
            preset: string,
            protocol: string,
            url: string,
        },
        {
            preset: string,
            protocol: string,
            url: string,
        },
        {
            preset: string,
            protocol: string,
            url: string,
        },
    ],
    comments: Comment[] | [],
    json: JSON,
}
